### ISSUE TITLE
Build from source fails

### ISSUE THREAD

**Issue by gregorkistler** [vmware/lightwave#10]
Hi,

I tried to build the RPM packages yesterday on two different photon machines but it always failed at the same step:

`compile:
[call-javac] Compiling 21 source files to /tmp/lightwave/vmafd/build/authentication-framework/authentication-framework/classes
[call-javac] error: error reading /tmp/lightwave/vmafd/build/depends/jna.jar; error in opening zip file
[call-javac] error: error reading /tmp/lightwave/vmafd/build/depends/platform.jar; error in opening zip file
[call-javac] error: error reading /tmp/lightwave/vmafd/build/depends/commons-logging-1.1.1.jar; error in opening zip file
[call-javac] error: error reading /tmp/lightwave/vmafd/build/depends/commons-lang-2.5.jar; error in opening zip file
[call-javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
[call-javac] 4 errors
[call-javac] 1 warning`

`BUILD FAILED
/tmp/lightwave/vmafd/interop/java/build.xml:15: The following error occurred while executing this line:
/tmp/lightwave/vmafd/build/ant/buildcycle-template.xml:80: Compile failed; see the compiler error output for details.`

`Total time: 0 seconds
Makefile:585: recipe for target '../../authentication-framework/packages/authentication-framework.jar' failed
make[4]: *** [../../authentication-framework/packages/authentication-framework.jar] Error 1
make[4]: Leaving directory '/tmp/lightwave/vmafd/build/interop/java'
Makefile:446: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/tmp/lightwave/vmafd/build/interop'
Makefile:480: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/tmp/lightwave/vmafd/build'
error: Bad exit status from /var/tmp/rpm-tmp.HqTeLj (%install)`

`RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.HqTeLj (%install)
Makefile.bootstrap:69: recipe for target 'package' failed
make[1]: *** [package] Error 1
make[1]: Leaving directory '/tmp/lightwave/vmafd/build'
Makefile:156: recipe for target '/tmp/lightwave/vmafd/build/rpmbuild/RPMS/x86_64/vmware-afd-6.6.0-4.x86_64.rpm' failed
make: *** [/tmp/lightwave/vmafd/build/rpmbuild/RPMS/x86_64/vmware-afd-6.6.0-4.x86_64.rpm] Error 2`

A couple of them were successfully created though so the pre-reqs are met:
vmware-directory-6.6.0-4.x86_64.rpm
vmware-directory-client-6.6.0-4.x86_64.rpm
vmware-directory-client-devel-6.6.0-4.x86_64.rpm
vmware-dns-6.6.0-3.x86_64.rpm
vmware-dns-client-6.6.0-3.x86_64.rpm
vmware-dns-client-devel-6.6.0-3.x86_64.rpm
vmware-event-devel-6.6.0-2.x86_64.rpm

Btw. additionally I had to install apache-ant and ant-contrib not just the mentioned likewise-open-devel package.

I the meantime I simply go with the pre-built ones.

Thanks

Gregor

**Comment by snambakam** [comment]
I created a new VM based on PhotonOS-1.0 on VMware Fusion, checked out Lightwave from the master branch and was able to build successfully.

Could you please build in /root/workspaces instead of in /tmp ?

I installed Photon Minimal and added additional packages - { git, make, binutils, automake, autoconf, libtool, gcc, rpm-devel, rpmbuild, linux-api-headers, util-linux-devel, gawk, openssl-devel, openssl, boost-devel, boost, python2-devel, createrepo, docker }. You could install PhotonOS Full.

**Comment by aizurov-vmw** [comment]
Hi Gregor,

Could you try the following:

tdnf -y install likewise-open-devel-6.2.9
tdnf -y install apache-ant
tdnf -y install ant-contrib

tdnf -y install boost-devel
tdnf -y install apache-tomcat
tdnf -y install jaxws-ri

before the build.

It may be that you were missing one of the last three dependencies (besides apache-ant and ant-contrib like you mentioned).

Thanks,
Andrei

**Comment by gregorkistler** [comment]
@snambakam and @aizurov-vmw thanks so far. I´ve double checked every step but still end up at the same error message.

Steps to reproduce (at least on my side):

1. Create a new VM in ESXi with default settings
2. Boot from the photon-1.0-13c08b6.iso (I´ve verified the sha1sum which is ebd4ae77f2671ef098cf1e9f16224a4d4163bad1)
3. Choose full installation method
4. After a reboot log in as root
5. run tdnf -y install likewise-open-devel apache-ant ant-contrib boost-devel apache-tomcat jaxws-ri
(hint: compiling with <= likewise-open-devel-6.2.9 doesn´t work anymore according to an error message so I´ve installed the latest and greatest version 6.2.10-1)
6. run git clone https://github.com/vmware/lightwave.git (current directory is /root .. but that shouldn´t really matter)
7. cd into the lightwave directory
8. run git checkout master (btw. this also happens with the default branch 'dev')
9. run make

**Comment by snambakam** [comment]
@gregorkistler : I followed your steps and got it to build successfully. I did _tdnf -y install likewise-open-devel-6.2.10-1_ first. The PhotonOS VM I created on ESXi has 1 GB RAM, 16 GB disk and 1 vCPU. Could you please check the disk space on your VM? I can help troubleshoot your build over WebEx; please let me know if this would be convenient for you and a convenient time.

**Comment by gregorkistler** [comment]
@snambakam thanks for the offer but I could sort it out on my own.
Since it also happened in a Virtualbox VM I checked the error messages again. The compiler complains about not to be able to unzip certain .jar files. I figured out that the files indeed were corrupt or actually not even .jar files at all.

Cause: certain build.xml files point to http://build-squid.eng.vmware.com which is only accessible from your corp network so in the end I got a DNS error message from my ISP saved as a jar.
I simply changed the urls to valid maven repositories and was able to build the RPMs.

Could you please update the vmca/jdepends/build.xml, vmafd/jdepends/build.xml and config/jdepends/build.xml with proper urls?

**Comment by snambakam** [comment]
Sorry about this omission. Thanks for pointing it out ! We will fix this as soon as possible.

**Comment by snambakam** [comment]
Fixed with commit 69438db26be699f2316dee7a5f4696d6d21cb794 on master.

Thanks for pointing out this issue !

**Comment by gregorkistler** [comment]
Cool, thanks.
