### ISSUE TITLE
Wiki documentation broken

### ISSUE THREAD

**Issue by casualjim** [vmware/lightwave#13]
The faq tells me to go to the microsite for photon but that link is broken

**Comment by wfu8** [comment]
By photon you mean Photon OS? What link to be exact? thanks

**Comment by casualjim** [comment]
The link is the Photon microsite in this section, on the wiki in this repo. 

https://github.com/vmware/lightwave/wiki/Frequently-Asked-Questions#q-what-kind-of-support-comes-with-project-lightwave

**Comment by johnnyferguson** [comment]
Thanks http://www.vmware.com/lightwave.html we'll sort that out.

**Comment by casualjim** [comment]
thanks for the link, I've updated the wiki with it
