### ISSUE TITLE
Options to destroy/uninstall an already configured domain

### ISSUE THREAD

**Issue by gregorkistler** [vmware/lightwave#14]
Is there currently any way to 'destroy' a lightwave domain after it was set up successfully?
If not, are there any plans to provide one?

**Comment by wfu8** [comment]
Can you please clarify what you mean by 'destroy' a lightwave domain? Do you mean 'demote' to support workflow such as re-promote existing stack to be a different domain?

**Comment by gregorkistler** [comment]
Lets say you set up a domain, notice that you made a typo or whatever and want to start from scratch again.
Currently the only way would be to start a new instance and install the lightwave packages again?

FreeIPA for example has a simple command to uninstall/destroy the current setup.
