### ISSUE TITLE
Lightwave UI is not functional after fresh installation

### ISSUE THREAD

**Issue by phoenyx762** [vmware/lightwave#58]
Deployed OVA "photon-hw13_uefi-3.0-a383732" within fusion 12
Followed the following installation process:
1. tdnf install -y lightwave
2. rpm -q --scripts openjre8 | grep -v postuninstall | grep -v posttrans > /tmp/test.sh
3. mv /etc/alternatives/jre/lib/ext /tmp
4. rm -rf /etc/alternatives/jre
5. bash /tmp/test.sh
6. mv /tmp/ext/*.jar /etc/alternatives/jre/lib/ext/
7. Edit /etc/hosts entries as per https://github.com/vmware/lightwave#set-up-the-hostname-for-the-instance Essentially, if the domain name is going to be lightwave.local and your hostname is photon-test, hostname should return photon-test and hostname -f should return photon-test.lightwave.local
8. /usr/bin/configure-lightwave-server --domain lightwave.local --password 'VMware123$'

When trying to access https://host.lightwave.local from my mac gives a blank page on Chrome, Firefox and Safari.

Used nmap to see if the ports were open:
Nmap scan report for 192.168.1.100
Host is up (0.00040s latency).
Not shown: 993 closed ports
PORT    STATE SERVICE
22/tcp  open  ssh
53/tcp  open  domain
88/tcp  open  kerberos-sec
135/tcp open  msrpc
389/tcp open  ldap
443/tcp open  https
| http-enum:
|_  /metrics/: Spring Boot Actuator endpoint
636/tcp open  ldapssl

Nmap done: 1 IP address (1 host up) scanned in 8.55 seconds

The page for metrics (https://host.lightwave.local/metrics) does work but nothing else does.

**Comment by snambakam** [comment]
The Lightwave UI is not part of the lightwave RPM.
The UI code is in the [ui](https://github.com/vmware/lightwave/tree/dev/ui) folder.
It is possible to build the Lightwave UI RPMs using the instructions in the [README.md](https://github.com/vmware/lightwave/tree/dev/ui/README.md)

At the current time, the Lightwave UI RPMs are not included in the Photon distributions.
